### ISSUE TITLE
CAS number not found

### ISSUE THREAD

**Issue by zhaochonghe** [USEPA/CompTox-ExpoCast-httk#12]
We want to process a  compound by httk, but neither its CAS number, name or dtxsid cannot be found by querying the function "get_cheminfo()". Does  httk only supports the compunds contained in R package? How to process our case?   Do we need to add the experimental data to fix the "get_cheminfo()"?

**Comment by jfwambaugh** [comment]
Hello, the intent of the function get_cheminfo is to list all the chemicals within HTTK where sufficient data are available for the specified model and species. If your chemical isn't listed you will need to add data for it using add_chemtable. I've updated the help for get_cheminfo to state:

This function lists information on all the chemicals within HTTK for which there are sufficient data for the specified model and species. By default the function returns only CAS (that is, info="CAS"). The type of information available includes chemical identifiers ("Compound", "CASRN", "DTXSID"), in vitro measurements ("Clint", "Clint.pvalue", "Funbound plasma", "Rblood2plasma"), and physico-chemical information ("Formula", "logMA", "logP", "MW", "pKa_Accept", "pKa_Donor"). The argument "info" can be a single type of information, "all" information, or a vector of specific types of information. The argument "model" defaults to "3compartmentss" and the argument "species" defaults to "human". Since different models have different requirements and not all chemicals have complete data, this function will return different numbers of chemicals depending on the model specified. If a chemical is not listed by get_cheminfo then either the in vitro or physico-chemical data needed are currently missing (but could potentially be added using \code{\link{add_chemtable}}.
