### ISSUE TITLE
Generic question

### ISSUE THREAD

**Issue by PARODBE** [USEPA/CompTox-ExpoCast-httk#5]
Hi!

Nice to meet you, and I have a generic question. If you want incorporate toxicokinetic information to qsar models, I think that this tool is very useful, but in your opinion which could be the most interesting variables? Kel,Vd,Css,Cl,Fub? And in this case are there a function? because when I am running a loop for calc_tkstats for all compounds, I am obtaining: 

Error in parameterize_pbtk(chem.cas = NULL, chem.name = c("2,2-bis(4-hydroxyphenyl)-1,1,1-trichloroethane (hpte)", : 
Missing metabolic clearance data for given species.

Thanks!
Pablo

**Comment by jfwambaugh** [comment]
Depending on what you're trying to predict Css might capture most of what you want, since Css is proportional to 1/CLtot, and CLtot = Vd*kelim (for a 1 compartment model). 

When you loop you want to use the get_cheminfo() function to identify the chemicals for which a given model will work, like get_cheminfo(model="1compartment").

So to get all the 1compartment parameters use this:

chem.descs <- NULL
for (this.chem in get_cheminfo(model="1compartment")) chem.descs <- rbind(chem.descs,c(this.chem,unlist(parameterize_1comp(chem.cas=this.chem))))

To get just Css use:
chem.descs <- NULL
for (this.chem in get_cheminfo(model="1compartment")) chem.descs<- rbind(chem.descs,c(this.chem,calc_analytic_css(chem.cas=this.chem,model="1compartment")))

The main other descriptor I might want to know is ionization state in plasma (pH=7.4):
chem.descs <- NULL
for (this.chem in get_cheminfo(model="1compartment")) chem.descs<- rbind(chem.descs,c(this.chem,calc_ionization(chem.cas=this.chem, pH=7.4)))

**Comment by PARODBE** [comment]
Uooh thank you so much!!! Very useful!!
